# Generated by Django 2.2.2 on 2019-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190625_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='Block',
            field=models.BooleanField(),
        ),
    ]
