# Generated by Django 2.2.2 on 2019-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190625_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='Admission_Year',
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='Academic_Year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='Academic_Year',
            field=models.CharField(max_length=10),
        ),
    ]
