# Generated by Django 2.2.2 on 2019-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190625_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Faculty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Semester',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Total_Classes',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='fees',
            name='Due_Date',
            field=models.CharField(default='-/-/-', max_length=10),
        ),
        migrations.AlterField(
            model_name='fees',
            name='Semester',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Semester',
            field=models.CharField(max_length=6),
        ),
    ]
