# Generated by Django 2.2.2 on 2019-06-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190626_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='Academic_Year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='Year_of_Passing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Faculty',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='staffeducation',
            name='Branch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffeducation',
            name='Teaching_Subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
