# Generated by Django 2.2.2 on 2019-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190626_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='Status',
            field=models.CharField(max_length=7),
        ),
    ]
