# Generated by Django 2.2.2 on 2019-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_fees_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Semester',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='fees',
            name='Semester',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='fees',
            name='Status',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Semester',
            field=models.CharField(max_length=8),
        ),
    ]
