# Generated by Django 2.2.2 on 2019-06-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_fees_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='Due_Date',
        ),
    ]
