# Generated by Django 2.2.2 on 2019-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_fees_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffinfo',
            old_name='Date_of_Birth',
            new_name='Date_of_Joining',
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='Department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='Designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
