# Generated by Django 2.2.2 on 2019-06-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190627_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='Department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='Designation',
            field=models.CharField(max_length=50),
        ),
    ]
