# Generated by Django 2.2.2 on 2019-06-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20190627_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='Profile_Picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
