# Generated by Django 2.2.2 on 2019-06-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_studentinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='Profile_Picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
