# Generated by Django 2.2.2 on 2019-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20190628_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='Profile_Picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
