# Generated by Django 2.2.2 on 2019-07-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20190703_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Student_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.StudentLogin', unique=True),
        ),
    ]
