# Generated by Django 2.2.2 on 2019-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20190703_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Profile_Picture',
            field=models.FileField(blank=True, default='profile_picture/student.png', null=True, upload_to='profile_picture/'),
        ),
    ]
